---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: drone
...
