---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone
  namespace: droneio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: drone
...
