---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  releaseName: plex
  chart:
    repository: https://charts.andrewmellen.org/
    name: kube-plex
    version: 0.3.1
  values:
    image:
      repository: mellena1/pms-docker
      tag: "1.0.0-1.18.9.2578-513b381af"
    kubePlex:
      enabled: true
      image:
        repository: mellena1/kube-plex
        tag: "0.1.0"
    timezone: America/New_York
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 300
      timeoutSeconds: 10
    claimToken:
      secret: claim-token
    persistence:
      data:
        claimName: plex
      config:
        claimName: plex-config
      transcode:
        enabled: true
        claimName: plex-transcode
    service:
      type: NodePort
      nodePort: 32400
    ingress:
      enabled: true
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "nginx"
      tls:
      - hosts:
        - plex.andrewmellen.org
        secretName: plex-letsencrypt-prod
      hosts:
      - plex.andrewmellen.org
...
