---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2500Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: plex
...
