---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-transcode
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: plex-transcode
...
