---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: devops
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.24.0
  values:
    controller:
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
        tag: 0.26.1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      reportNodeInternalIp: true
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
...
