---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: devops
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 3.21.0
  values:
    controller:
      image:
        tag: 0.43.0
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      reportNodeInternalIp: true
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
...
