---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: devops
spec:
  releaseName: cert-manager
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: cert-manager
    version: v0.5.0
  values:
    resources:
      requests:
        memory: 20Mi
...
