---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: devops
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.14.1
  values:
    global:
      leaderElection:
        namespace: devops
    resources:
      requests:
        memory: 20Mi
...
