---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: metrics
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://charts.helm.sh/stable/
    name: prometheus-operator
    version: 8.12.3
  values: {}
...
