---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
  labels:
    app: drone
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.200
    path: "/nas/drone"
...
