---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
  labels:
    app: drone
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: "/nas/drone"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homek8s
...
