---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
  labels:
    app: plex-transcode
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.200
    path: "/nas/plex-transcode"
  persistentVolumeReclaimPolicy: Recycle
...
