---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
  labels:
    app: plex-transcode
spec:
  capacity:
    storage: 250Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    path: "/mnt/homek8s/plex-transcode"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homek8s
...
