---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    app: plex-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.200
    path: "/opt/plex-config"
  persistentVolumeReclaimPolicy: Recycle
...
