---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex
  labels:
    app: plex
spec:
  capacity:
    storage: 2500Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.200
    path: "/nas/plex"
  persistentVolumeReclaimPolicy: Recycle
...
