---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    app: plex-config
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    path: "/mnt/homek8s/plex-config"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homek8s
...
