---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: devops
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://charts.helm.sh/stable/
    name: sealed-secrets
    version: 1.0.1
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.7.0
    crd:
      keep: false    
...
