---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: destiny-rank-calculator
  namespace: randomwebapps
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:*
spec:
  releaseName: destiny-rank-calculator
  chart:
    repository: https://charts.andrewmellen.org/
    name: std-webapp
    version: "0.1.1"
  values:
    image:
      repository: mellena1/destiny-rank-calculator
      tag: "0.3.0"
    nameOverride: destiny-rank-calculator
    ingress:
      enabled: true
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "nginx"
      tls:
      - hosts:
        - destinycalc.andrewmellen.org
        secretName: destinycalc-letsencrypt-prod
      hosts:
      - host: destinycalc.andrewmellen.org
        paths:
        - /
